name: Monthly Album Poster

on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  post_album:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install pylast python-dotenv mastodon python-dateutil

    - name: Run the script
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
        LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        LASTFM_PASSWORD: ${{ secrets.LASTFM_PASSWORD }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
        MASTODON_BASE_URL: ${{ secrets.MASTODON_BASE_URL }}
      run: python main.py
